# ══════════════════════════════════════════════════════════
#  Stage 1: base

# ══════════════════════════════════════════════════════════
FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@latest --activate


# ══════════════════════════════════════════════════════════
#  Stage 2: deps
# ══════════════════════════════════════════════════════════
FROM base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile


# ══════════════════════════════════════════════════════════
#  Stage 3: build
# ══════════════════════════════════════════════════════════
FROM base AS build
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN pnpm prisma generate
RUN pnpm next build


# ══════════════════════════════════════════════════════════
#  Stage 4: runner
# ══════════════════════════════════════════════════════════
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=build /app/package.json ./
COPY --from=deps  /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/prisma.config.ts ./
COPY --from=build /app/generated ./generated

COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
